// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mB5QnwFJ1OhR6aEuY6X54eGW-nEf5rw',
    appId: '1:989609807796:web:63bf651699a97ba4872ce1',
    messagingSenderId: '989609807796',
    projectId: 'dogar-dairy',
    authDomain: 'dogar-dairy.firebaseapp.com',
    databaseURL: 'https://dogar-dairy-default-rtdb.firebaseio.com',
    storageBucket: 'dogar-dairy.firebasestorage.app',
    measurementId: 'G-QWSRL838P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDno8__YEb6YQvtAiUvVHeayUD-ql_PFFA',
    appId: '1:989609807796:android:1b33f2700f84d13b872ce1',
    messagingSenderId: '989609807796',
    projectId: 'dogar-dairy',
    databaseURL: 'https://dogar-dairy-default-rtdb.firebaseio.com',
    storageBucket: 'dogar-dairy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1AZVbzdNn-G6MPGfaR_vlHuSRhgrDeY',
    appId: '1:989609807796:ios:0e93a0839f9e26b7872ce1',
    messagingSenderId: '989609807796',
    projectId: 'dogar-dairy',
    databaseURL: 'https://dogar-dairy-default-rtdb.firebaseio.com',
    storageBucket: 'dogar-dairy.firebasestorage.app',
    iosBundleId: 'com.example.dogardairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT1AZVbzdNn-G6MPGfaR_vlHuSRhgrDeY',
    appId: '1:989609807796:ios:0e93a0839f9e26b7872ce1',
    messagingSenderId: '989609807796',
    projectId: 'dogar-dairy',
    databaseURL: 'https://dogar-dairy-default-rtdb.firebaseio.com',
    storageBucket: 'dogar-dairy.firebasestorage.app',
    iosBundleId: 'com.example.dogardairy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1mB5QnwFJ1OhR6aEuY6X54eGW-nEf5rw',
    appId: '1:989609807796:web:d558c0c7a079a06b872ce1',
    messagingSenderId: '989609807796',
    projectId: 'dogar-dairy',
    authDomain: 'dogar-dairy.firebaseapp.com',
    databaseURL: 'https://dogar-dairy-default-rtdb.firebaseio.com',
    storageBucket: 'dogar-dairy.firebasestorage.app',
    measurementId: 'G-9QLWWQHZ4E',
  );
}
